### ISSUE TITLE
postman /auth/refresh returns error

### ISSUE THREAD

**Issue by AnyGong** [andrechristikan/ack-nestjs-boilerplate-mongoose#13]
I am honored to use this library. Thanks to the author for the creation. I have found a problem in use.

`{{refreshToken}}` has used the refreshToken value returned after login, set it to postman's global variable refreshToken

```json
{
    "statusCode": 5103,
    "message": "Unauthorized"
}
```

**Comment by andrechristikan** [comment]
Hi @AnyGong ,
Sorry for the delay in updating the Usage Document

The configuration of Auth is
- `expiredTime` of `refreshToken ` is `8d`
- `notBeforeExpiredTime` of `refreshToken` is `1d`
- `expiredTime` of `accessToken` is `1d`
- `notBeforeExpiredTime ` of `accessToken` is `0`

which means 
- `AccessToken` can be use it immediately, and will expire in 1 day 
- But `RefreshToken` can be use after access token has expired (1 day after create), and will expire in 8 days

you can find the configuration in config file, path is `src/config/auth.config.ts`
```ts
...
...

jwt: {
    accessToken: {
        secretKey:
            process.env.AUTH_JWT_ACCESS_TOKEN_SECRET_KEY || '123456',
        expirationTime: '1d',
        notBeforeExpirationTime: '0'
    },

    refreshToken: {
        secretKey:
            process.env.AUTH_JWT_REFRESH_TOKEN_SECRET_KEY ||
            '123456000',
        expirationTime: '8d',
        notBeforeExpirationTime: '1d' // <<< ---- here the value
    },

    rememberMe: {
        notChecked: 7, // in days
        checked: 30 // in days
    }
},

...
...
```

Change 'jwt.refreshToken.notBeforeExpirationTime' to '0' will resolve the issue.
After changing the value, you must re-run this project, and re-login to `receive the newRefreshToken with 0 value of notBeforeExpirationTime`

Hope this will help you, thank you

**Comment by AnyGong** [comment]
Thank you very much for your reply, as a beginner in nestjs, this project is very useful, thank you again for creating this library
