### ISSUE TITLE
Access a route with regular and admin user as well.

### ISSUE THREAD

**Issue by MatyasK** [andrechristikan/ack-nestjs-boilerplate-mongoose#140]
I find it interesting that there is nothing implemented to check authentication for routes which can be accessed with any role. Or I just missed something?

**Comment by MatyasK** [comment]
nvm I can use just the regular AuthJwtGuard

**Comment by andrechristikan** [comment]
Yup that right, you can use the `AuthJwtGuard`, that only check for user active, role active, and permission active (conditional).
