### ISSUE TITLE
Error: Nest can't resolve dependencies of the LoggerService (?). Please make sure that the argument LoggerEntityModel at index [0] is available in the LoggerModule context.

### ISSUE THREAD

**Issue by helxsz** [andrechristikan/ack-nestjs-boilerplate-mongoose#148]
I am starting to learn nestjs, but after installing all the packages from the npm install, npm run start gives me an error saying :
_[Nest] 6445  - 24/05/2022, 12:50:27   ERROR [ExceptionHandler] Nest can't resolve dependencies of the LoggerService (?). Please make sure that the argument LoggerEntityModel at index [0] is available in the LoggerModule context.

Potential solutions:
- If LoggerEntityModel is a provider, is it part of the current LoggerModule?
- If LoggerEntityModel is exported from a separate @Module, is that module imported within LoggerModule?
  @Module({
    imports: [ /* the Module containing LoggerEntityModel */ ]
  })

Error: Nest can't resolve dependencies of the LoggerService (?). Please make sure that the argument LoggerEntityModel at index [0] is available in the LoggerModule context.

Potential solutions:
- If LoggerEntityModel is a provider, is it part of the current LoggerModule?
- If LoggerEntityModel is exported from a separate @Module, is that module imported within LoggerModule?_

![Screenshot 2022-05-24 at 12 54 01](https://user-images.githubusercontent.com/669670/169951897-b26d94d2-11dd-46c8-995e-418b1fdf3c54.png)

I have no idea what goes wrong with loggerService and how to solve the issue

**Comment by andrechristikan** [comment]
Hi @helxsz 
can you share the `LoggerModule` code and the `LoggerService` ?

**Comment by sarkstephan** [comment]
For me It happens after `yarn upgrade --latest` for @nestjs/mongoose
This is why there are issues injecting mongoose models.
It's not specifically related to LoggerService, this will happen to any service tho
stable with @nestjs/mongoose@9.0.3

**Comment by andrechristikan** [comment]
Thankyou @sarkstephan 
You right, that because of `@nestjs/mongoose` version update and this boiler use custom connection name 

```ts
@Global()
@Module({
    providers: [LoggerService],
    exports: [LoggerService],
    imports: [
        MongooseModule.forFeature(
            [
                {
                    name: LoggerEntity.name,
                    schema: LoggerSchema,
                    collection: LoggerDatabaseName,
                },
            ],
            DATABASE_CONNECTION_NAME // <--- here
        ),
    ],
})
export class LoggerModule {}
```

To resolve the problem, we need to put custom connection name in `@InjectModel` too.

```ts
export function DatabaseEntity(
    entity: string,
    connectionName?: string
): (target: Record<string, any>, key: string | symbol, index?: number) => void {
    return InjectModel(entity, connectionName || DATABASE_CONNECTION_NAME); // <--- here
}
```

By the way, i have done update this boiler. Go get the newest.
