### ISSUE TITLE
Environment variable read error

### ISSUE THREAD

**Issue by AnyGong** [andrechristikan/ack-nestjs-boilerplate-mongoose#15]
kafka is not enabled, but the file for environment variables reads `kafka/.env.example`

**Comment by andrechristikan** [comment]
Hi @AnyGong 
Do you still receive this error ?

If yes, you can reproduce the error and reopen the issue again
Don't forget to give detail about you error

Thanks

**Comment by AnyGong** [comment]
Sorry for the trouble! It was an accident, when I replaced the file code, I made a mistake in the file name of the read variable.
