### ISSUE TITLE
found real emails in log files

### ISSUE THREAD

**Issue by mohamedmostafaa** [andrechristikan/ack-nestjs-boilerplate-mongoose#152]
hello sir,
many thanks for your great effort to build something like that,
can you explain to me why in the server log files i found real email and i tried so hard to foud where they come from
here the log file 

`'::ffff:127.0.0.1' - '-' - '[2022-05-31T16:39:38.153Z]' - 'HTTP/1.1' - '[200]' - 'GET' - '/health/database' - 'Request Header :: {
> {"_id":"62964577e5cf5e793d7f7dfc","firstName":"josianne_roob@gmail.com","lastName":"bradtke","mobileNumber":"62812378789821","email":"josianne_roob@gmail.com","isActive":true,"createdAt":"2022-05-31T16:42:31.698Z"}]

> {"firstName":"Annabel","lastName":"Koss","password":"@!maryCURTIS44","email":"Alexanne.Heathcote@gmail.com","mobileNumber":"62812233040271","role":"62964578e5cf5e793d7f7e15"}'

 

> {"firstName":"Annabel","lastName":"Koss","password":"@!maryCURTIS44","email":"josianne_roob@gmail.com","mobileNumber":"62812378789821","role":"62946993d8a7379004cd1630"}' - 'Response Header :: -' - 'Response Body :: 

`

**Comment by andrechristikan** [comment]
That because i put all the `req.body` and `res.body` into the log file.

If you do not want put any sensitive data into the log file, you can edit the log format in `src/utils/middleware/http-debugger/http-debugger.constant.ts` and remove the `req.body` and `res.body`

like this
```ts
export const DEBUGGER_HTTP_FORMAT =
    "':remote-addr' - ':remote-user' - '[:date[iso]]' - 'HTTP/:http-version' - '[:status]' - ':method' - ':url' - 'Request Header :: :req-headers' - 'Request Params :: :req-params' - 'Response Header :: :res[header]' - ':response-time ms' - ':referrer' - ':user-agent'";
```

For more information you can read [morgan](https://www.npmjs.com/package/morgan)
