### ISSUE TITLE
swageer module

### ISSUE THREAD

**Issue by AnyGong** [andrechristikan/ack-nestjs-boilerplate-mongoose#16]
Will you consider accessing `swagger` ？

**Comment by mikeychowy** [comment]
yes please, would help very much with development

**Comment by andrechristikan** [comment]
sound good, 
it is gonna helpful our development phase

okay,... i will go to add the swagger after i finished writing the `TestingModule` (unit testing and e2e testing)
or maybe you guys can add that and then create the PR.
