### ISSUE TITLE
About ErrorLogInterceptor on Guard error not work

### ISSUE THREAD

**Issue by jiayisheji** [andrechristikan/ack-nestjs-boilerplate-mongoose#212]
After Guard throws an error, the ErrorLogInterceptor RXJS catchError no longer catches errors.

**Comment by andrechristikan** [comment]
Yes, you right and that was happen by mistake

**Comment by andrechristikan** [comment]
I guess that because of nestjs request lifecycle.

The issue will be fixed in the next release with nestjs v9x 🚀
