### ISSUE TITLE
OAuth2 Client Credentials

### ISSUE THREAD

**Issue by aronfelipe** [andrechristikan/ack-nestjs-boilerplate-mongoose#242]
Are you interested in implementing client credentials?

I would help.

Just let me know.

**Comment by andrechristikan** [comment]
Hi @aronfelipe,

Is this a reference to an [OAuth2 Client Credential](https://www.oauth.com/oauth2-servers/access-tokens/client-credentials/) ?

If yes, well... it sounds good ! 
If you don't mind, feel free to create a PR. 
Then I will check it 😁

**Comment by aronfelipe** [comment]
Hi @andrechristikan,

That's right. I will work on it.

**Comment by aronfelipe** [comment]
Would you create a branch for me and let me do changes on it? @andrechristikan

**Comment by andrechristikan** [comment]
Unfortunately, I am unable to do so. 
However, you can make changes by submitting a pull request or PR 😁

[Here some reference](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork).
