### ISSUE TITLE
Are you guys following Restful Api conventions? if yes then why action like update, delete are part of Urls?

### ISSUE THREAD

**Issue by akashabbasi** [andrechristikan/ack-nestjs-boilerplate-mongoose#246]

**Comment by andrechristikan** [comment]
No, I do not follow that.

This is my personal opinion. 
In microservice architecture, they have a component named Restful API.

Simply, Restful API use as bridge between backend and frontend.
So, whatever you do in the frontend, like create/update/delete/ or even read (CRUD), that must pass via the Restful API. 
Your frontend does have the capability of doing CRUD directly.

This answer will differ from your case, especially if you use monolithic architecture.

Hopefully, this will help you.

**Comment by akashabbasi** [comment]
So if i use this  boilerplate for a monolith app. Should i rename routes to restful naming conventions like 
PUT /users/update/:user -> PUT /users/:id?

**Comment by andrechristikan** [comment]
I think that is just the same. You can choose whatever you like. 
That is just the style among developers.
