### ISSUE TITLE
Pagination decorators aren't working as expected

### ISSUE THREAD

**Issue by akashabbasi** [andrechristikan/ack-nestjs-boilerplate-mongoose#259]
I am using this boilerplate as starting point of my project. i have used generic pagination decorators (code borrowed from this repo) but they aren't working as expected. When i call the endpoint with query params. Query params are available till Interceptor. but  after validating it against Listing Dto  in router handler params. all values of Dto are undefined.

**Comment by andrechristikan** [comment]
I think that's because of [nestjs request life cycle](https://docs.nestjs.com/faq/request-lifecycle)
Our dto will serialize with `class-transformer` and then validate with `class-validation` from `typestack`. 
The entire process will be carried out in the `ValidationPipe` from `@nestjs/common` as a `global pipe`.

As you can see in the doc request life cycle, the global pipe will run after the pre-interceptor. 
That why you query params only accessable in interceptor.

So, I guess your problem comes because of the wrong implementation options of ValidationPipe. 
Try to set `false` for `whitelist` options, maybe that will help to solve your problem.

[Here if you need to read more documentation about ValidationPipe](https://docs.nestjs.com/techniques/validation#validation)

**Comment by akashabbasi** [comment]
I have tried to make it work by setting IsOptional decorator on properties which we don't expect from front-end like availableSort & availableSearch. Without this decorator inside controller these properties were not accessible. 

But my problem still exist with search property. Transform decorator for search tries to create regex for each value inside availableSearch array. my question is how we can make it work for non-string values? 

How we can make sorting to work with multiple values at same time

**Comment by akashabbasi** [comment]
Like currently search decorator i guess is working like this. it only works for property of string type and lets say we pass search=abc then if available search is on ['firstname', 'email'] then search decorator will transform the values for both firstname and email. and it will be search in database then

**Comment by andrechristikan** [comment]
Yes, correct! That will work with `string type or number type only`, and then it depends on `AvailableSearch`. 
The logic of search is only for simple usage. 
The search will use regex to make it case insensitive and contain some value.


eg: 
```json
{
    "name": {
        "first": "ack",
        "last": "mongoose"
    },
    "phone": "621313121111",
    "email": "blabla@mail.com"
}
```

and then, you can make AvailableSearch like this to search inside the object.
```ts
const availableSearch = [
    'name.first',
    'name.last',
    'name',
]
```

Okay, there are 2 questions.

1. How we can make it work for non-string values?

If you want to advance usage, I suggest you make an edit to `PaginationModule` with your logic.
For the current version, look in `src-> common-> pagination-> decorator-> pagination.decorator.ts -> PaginationSearch`, and then edit the `@Transform` Decorator. 

2. How we can make sorting to work with multiple values at same time?

Same with answer 1. You must change the `@Transform` Decorator in `PaginationSort` with your own logic. 
The current sort decorator only supports 1 sort.

**Comment by andrechristikan** [comment]
Or you can add more `PaginationFilter` for other cases.

**Comment by andrechristikan** [comment]
The problem you have about not accessible property in controller, maybe because of `ValidationPipe`

```ts
@Module({
    controllers: [],
    providers: [
        {
            provide: APP_PIPE,
            useFactory: () =>
                new ValidationPipe({
                    transform: true, // <-- try to set it with true
                    whitelist: false, // <-- try to set it with false
                    skipNullProperties: false, // <-- try to set it with false
                    skipUndefinedProperties: false, // <-- try to set it with false
                    skipMissingProperties: false, // <-- try to set it with false
                    errorHttpStatusCode: HttpStatus.UNPROCESSABLE_ENTITY,
                    exceptionFactory: async (errors: ValidationError[]) =>
                        new UnprocessableEntityException({
                            statusCode:
                                ENUM_REQUEST_STATUS_CODE_ERROR.REQUEST_VALIDATION_ERROR,
                            message: 'http.clientError.unprocessableEntity',
                            errors,
                        }),
                }),
        },
    ],
    imports: [],
})
export class RequestModule {}
```

**Comment by akashabbasi** [comment]
Thanks for your response. if you can provide postman collection you used to test the endpoints of this repo. it would be very helpful as i have some confusion related to passing some of query params to these endpoints.

**Comment by andrechristikan** [comment]
Sure, i will.
Endpoint will describe with swagger (on progress) and i will update the documentation.
Stay tuned😁

**Comment by andrechristikan** [comment]
Hi @akashabbasi,
I already done to add the API Spec with swagger, go check the current version 
Thank you 😁

**Comment by akashabbasi** [comment]
Let me check it :+1:
