### ISSUE TITLE
How to implement operation record

### ISSUE THREAD

**Issue by jiayisheji** [andrechristikan/ack-nestjs-boilerplate-mongoose#266]
I know how to use a DTO to implement the update field diff.
I know that the controller uses decorator tag operations to record actions.
I know that interceptors are used global to commit operation records to the database.

How do you determine the request context and the operational user?

I designed the request context service class to bind a request ID,

use `{ scope: Scope.REQUEST }`

get `request: Request` user

Is there a better implementation?

update-user.dto.ts

```ts
class UpdateUserDto {
     @DiffField('username')
     name: string;
}
```

user.controller.ts

```ts
class UserController {
    @Put(':id')
    @UpdateRecordLog(
      'update user ${entity.name}',
      'user ${entity.name} update field ${patch.name} form ${patch.origin} to ${patch.current}'
    )
    update(@Param('id', ParseIntPipe) id: number, @Body() dto: UpdateUserDto) {
      return this.UserService.update(id, dto);
    }
}
```

user.service.ts

```ts
class UserService {
     constructor(
      private userRepository: UserRepository,
      private requestContext: RequestContext
    ) {}
    update(id: number, dto: UpdateUserDto) {
      const result =  this.userRepository.update(id, dto);
      this.recordContext.put(result);
      return result;
    }
}
```

request-context.ts

```ts
const map: Map<string, Record<string, unknown>> = new Map();

@Injectable({ scope: Scope.REQUEST })
export class RequestContext {
  static setRecordKeyForRequest(request: Request) {
    request[RecordContextMetadataKey] = uuid.v1();
  }

  static getRecordKeyForRequest(request: Request): string | undefined {
    return request[RecordContextMetadataKey];
  }

  static get(recordKey: string) {
    const value = map.get(recordKey);
    map.delete(recordKey);
    return value;
  }

  constructor(@Inject(REQUEST) private request: Request) {}

  put(data) {
      const recordKey = RequestContext.getRecordKeyForRequest(this.request);
      if (recordKey == null) {
       throw new Error('recordKey is not defined');
     }
     map.set(recordKey, data);
  }
}
```

record.interceptor.ts

```ts

@Injectable()
export class RecordInterceptor implements NestInterceptor<unknown> {
  constructor(
    @Inject(LoggerService) private readonly loggerService: LoggerService
  ) {}

  intercept(
    context: ExecutionContext,
    next: CallHandler<unknown>
  ): Observable<unknown> {
    const call$ = next.handle();

    const record_meta = Reflect.getMetadata(RECORD_META, context.getHandler());

    // Logs do not need to be reported
    if (record_meta == null) {
      return call$;
    }
    
    const { request } = ExpressContext(context);
    // bind  request ID to request context
    RequestContext.setRecordKeyForRequest(request);
    return call$.pipe(
      map((data: unknown) => {
        // record to database
        // request.user to operator
        return data;
      })
    );
  }
}
```

**Comment by andrechristikan** [comment]
Based on my experience, if the provider scope is set to `request` and the request scope provider is injected to another provider. Then, other providers will be forced to request scope too.

So, if you inject the request scope provider into every provider (in the service layer), `that will decrease your application performance`.

ex:
1. without request context
```txt
service1 (scope default) -> controller1 (scope default)
service1 (scope default) -> controller2 (scope default)
```

2. with request context
```txt
requestContext (scope request) -> service1 (scope request) -> controller1 (scope request)
requestContext (scope request) -> service1 (scope request) -> controller2 (scope request)
```

Definition of request Scope from nestjs official doc
> A new instance of the provider is created exclusively for each incoming request. The instance is garbage-collected after the request has completed processing.


Maybe you should try this approach
> Cons `RequestId` will undefined in exception filter.

1. UserService, remove the request context
```ts
class UserService {
     constructor(
      private userRepository: UserRepository,
    ) {}
    update(id: number, dto: UpdateUserDto) {
      const result =  this.userRepository.update(id, dto);
      return result;
    }
}
```

2. UserController, i don't really know what happen with `@UpdateRecordLog`. I assume the `@UpdateRecordLog` is decorator group between `RecordInterceptor` and `RECORD_META `
```ts
class UserController {
    @Put(':id')
    @UpdateRecordLog(
      'update user ${entity.name}',
      'user ${entity.name} update field ${patch.name} form ${patch.origin} to ${patch.current}'
    )
    update(@Param('id', ParseIntPipe) id: number, @Body() dto: UpdateUserDto) {
      return this.UserService.update(id, dto);
    }
}
```

3. Record Interceptor, you do not need `RequestContext `
```ts
@Injectable()
export class RecordInterceptor implements NestInterceptor<unknown> {
  constructor(
    @Inject(LoggerService) private readonly loggerService: LoggerService
  ) {}

  intercept(
    context: ExecutionContext,
    next: CallHandler<unknown>
  ): Observable<unknown> {
    const call$ = next.handle();

    // ! set request id here
    const requestId = uuid.v1();

    const record_meta = Reflect.getMetadata(RECORD_META, context.getHandler());

    if (record_meta == null) {
      return call$;
    }
    
    return call$.pipe(
      tab(async (data: unknown) => {
        // !data is response from controller
        // !you can insert the record in this

        // for example, insert data into loggerservice
        await this.loggerService.put(requestId , data);
        return data;
      })
    );
  }
}
```

For the next, try to put the `RequestId` in middleware and then put the `RequestId` into `RequestContext` from express.

Ex: 
to put look `src/common/middleware/request-id.middleware.ts` in this project
to get look `src/common/logger/interceptors/logger.interceptor.ts` in this project
also you can get in `exception filter`, look `src/common/error/filters/error.http.filter.ts`

Do not forget to read the `https://docs.nestjs.com/faq/request-lifecycle`. This doc will (maybe) help you

**Comment by jiayisheji** [comment]
Thank you for your reply.

I want to make an operation log feature，record user actions, creation, modification, and deletion.

Each record needs to have an operator.

For the modification action, the modified field and the value before the modification and the value after the modification are required.

Developers can customize the format output record content.

**Comment by andrechristikan** [comment]
Ohh, I see... 
I can only recommend that you try using the `interceptor pre` and `interceptor post` instead of injecting `request context` into every service provider.

Hope you got the new insight.

**Comment by jiayisheji** [comment]
I know，`Interceptor` is the best choice. 
It was a pleasure talking to you. Thank you very much.
I'll show you when I write the code.
