### ISSUE TITLE
Example SPA app Using ACK NestJs

### ISSUE THREAD

**Issue by yavuzgunay** [andrechristikan/ack-nestjs-boilerplate-mongoose#280]
Hello, I really like your project. Can you share a simple SPA project where we can test the backend project?

**Comment by andrechristikan** [comment]
Is SPA means Single Page Application?

If yes, is SPA like swagger ui will help you?

**Comment by andrechristikan** [comment]
Hi @yavuzgunay ,
The API Reference has been deployed. You can visit [here](https://github.com/andrechristikan/ack-nestjs-mongoose#api-reference)
