### ISSUE TITLE
Problem with creating new Types.ObjectId  from String _id

### ISSUE THREAD

**Issue by salviosage** [andrechristikan/ack-nestjs-boilerplate-mongoose#3]
Getting Error while Starting the application 
```
src/logger/logger.service.ts:39:38 - error TS2554: Expected 0 arguments, but got 1.

39             user: new Types.ObjectId(user),
```

not sure but seems like new Types.ObjectId() doesn't expect any argument . and I am wondering if there is any way around of creating ObjectId from String

**Comment by andrechristikan** [comment]
Hi @salviosage, `Types.ObjectId()` is a class from mongoose that use for create `random object id` or `object id from ObjectIdString`.

E.g
Let assume `ObjectIdClass` will return `4eb6e7e7e9b7f4194e000001` as `ObjectIdString`
```ts
const ObjectIdClass: Types.ObjectId = new Types.ObjectId(); // will return object id class
const ObjectIdString: string = `${_id}`; // will return 4eb6e7e7e9b7f4194e000001
```

In `LoggerService`, you must pass `ObjectIdString` to fill `user param` not the random string.
E.g
```ts
this.loggerService.info(
  ENUM_LOGGER_ACTION.LOGIN, 
  'Description about the logger', 
  '4eb6e7e7e9b7f4194e000001', 
  [
      'login', 
      'fromMobile', 
      'withEmail'
  ]
);
```

But if my answer doesn't help you, you can give me more information about how you used `LoggerService`.
