### ISSUE TITLE
Remove "format:e2e": "prettier --write e2e/**/*.ts" from package.json

### ISSUE THREAD

**Issue by yonashalefom** [andrechristikan/ack-nestjs-boilerplate-mongoose#304]
"format:e2e": "prettier --write e2e/**/*.ts" which is found in package.json is not functional. So that is causing the following error while formatting the code with prettier. 

```
$ prettier --write e2e/**/*.ts
[error] No files matching the pattern were found: "e2e/**/*.ts".
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

So please remove that. Thanks! You guys are awesome!

**Comment by andrechristikan** [comment]
Thanks for mentioning it, really helpful.
