### ISSUE TITLE
Integration with GraphQL

### ISSUE THREAD

**Issue by yonashalefom** [andrechristikan/ack-nestjs-boilerplate-mongoose#310]
Firstly this is an awesome repo. We really appreciate the time and effort you put to this repository.

But if it is possible can you please update this repo to support GraphQL. That would be really awesome. Thanks!

**Comment by andrechristikan** [comment]
It sounds great!
Yeah.. I'm considering making this project support GraphQL too. 
Maybe to make that happen, the project will consume design of Domain-driven design (DDD).
 
But I do not know when the time has come. For now on, I'm really busy :)

**Comment by yonashalefom** [comment]
Maybe if you suggest the approach, my friend and I can help in integrating GraphQL with this repo. We're familiar with GraphQL, but we're not sure what the appropriate and clean (or better) method is to integrate GraphQL with this repo. We sincerely wish to help.

**Comment by andrechristikan** [comment]
You guys are awesome. 
That would be helpful. I really appreciate it !!!

If we want to implement GraphQL, so will the change request life cycle. I think we need to fully consume the design of clean architecture or hexagonal architecture, and that will cause a lot of breaking changes. Actually, I'm fine with breaking changes, as long as it resolve our problems.

Example of breaking changes

## Request life cycle

* current
   The client only accesses endpoints through Rest.

   1. client
   2. controller layer
   3. service layer
   4. repository layer
   5. db layer

* new
   The client can choose whatever they want to use between the Rest or GraphQL.

    1. client
    2. incoming request layer / rest controller or graph controller
    3. controller layer
    4. service layer
    5. repository layer
    6. db layer

## Implement CRQS

We need to consume the CRQS pattern so we can resolve the problem of the difference in incoming request layer.

Or do you guys have better implementation ? Feel free to discuss.

**Comment by yonashalefom** [comment]
This sounds awesome! We will implement this method. If we have questions we will mention it here.

**Comment by jiayisheji** [comment]
The hexagon structure about nestjs guide at [https://github.com/Sairyss/domain-driven-hexagon](https://github.com/Sairyss/domain-driven-hexagon). I'm learning, too.
