### ISSUE TITLE
Import and use another services

### ISSUE THREAD

**Issue by DexVN** [andrechristikan/ack-nestjs-boilerplate-mongoose#367]
I want to test the method usage of another service and get an error. How can I get this to work. I'm just testing

"Nest can't resolve dependencies of the UserService (UserRepository, ?, HelperDateService, HelperStringService, ConfigService). Please make sure that the argument RoleService at index [1] is available in the UserModule context."

**Comment by andrechristikan** [comment]
Sure

**Comment by andrechristikan** [comment]
Make sure to keep the whole service is independent and avoid circular dependency.

I guess that issue because you using some module but you don't import the dependency.
For resolve your issue, you can do this
```ts
@Module({
  exports: [
    RoleModule // <-- add this
  ],
  imports: [],
  providers: [],
  controllers: []
})
export class UserModule {}
```
