### ISSUE TITLE
Boilerplate Error

### ISSUE THREAD

**Issue by rajkrajpj** [andrechristikan/ack-nestjs-boilerplate-mongoose#368]
Upon forking from [[4a5c348](https://github.com/andrechristikan/ack-nestjs-boilerplate/commit/4a5c348c8d875cb413e3dfa0a7fac8a500bf5ae0)](https://github.com/andrechristikan/ack-nestjs-boilerplate/commit/4a5c348c8d875cb413e3dfa0a7fac8a500bf5ae0)

After installing dependencies and running `npm run start:dev` or `npm run seed`.

The error: `<project>/src/common/database/abstracts/mongo/entities/database.mongo.uuid.entity.abstract.ts:19
    static { _a = database_constant_1.DATABASE_DELETED_AT_FIELD_NAME, _b = database_constant_1.DATABASE_CREATED_AT_FIELD_NAME, _c = database_constant_1.DATABASE_UPDATED_AT_FIELD_NAME; }` occurs despite no code changes.

**Comment by andrechristikan** [comment]
There is no error in my local test, maybe that error because of difference of our env.

Can you provide some information
Which version you use
1. NPM
2. NodeJs
3. Yarn
4. MongoDB
5. MongoDB Replication or Single Node

**Comment by CaoThien96** [comment]
I also got the same error. Caused by the version of node. Node >16 is work

**Comment by andrechristikan** [comment]
Yup, I think so.
I've already tested in versions 16 and 18. There are no errors.

**Comment by rajkrajpj** [comment]
Thanks resolved it as well guys! Closing issue now
