### ISSUE TITLE
the demo isnt working

### ISSUE THREAD

**Issue by ratnabh-classic** [andrechristikan/ack-nestjs-boilerplate-mongoose#398]
I just cloned the project, and changed the db config to connect it to mongo atlas. However, I see an error which is hard to track here.
As soon as i navigate to route http://localhost:4000/docs#/hello
and try the very first section i am getting error, Please refer to the screenshot below 
<img width="1121" alt="Screenshot 2023-03-29 at 10 41 29 AM" src="https://user-images.githubusercontent.com/80817066/228432797-58f42a94-a4bf-4cd9-9dbe-e78af8a3cb27.png">

**Comment by andrechristikan** [comment]
I guess, you forgot to seeding your database
