### ISSUE TITLE
Docker compose service dependency to ackDatabase

### ISSUE THREAD

**Issue by rezasadeqzadeh** [andrechristikan/ack-nestjs-boilerplate-mongoose#410]
Hello,

There is a service dependency ackDatabase for service in docker-compose file that there is not exist in the docker-compose.yml

I think the service should depend on mongo1 service. Am I right?

**Comment by andrechristikan** [comment]
Ohh yeah.. that right
Thank you for your report

Please read the newest read.me, i already fix `.docker-compose.yml` add more instructions to run with docker
