### ISSUE TITLE
role creation

### ISSUE THREAD

**Issue by solomonmulatu** [andrechristikan/ack-nestjs-boilerplate-mongoose#423]
while creating custom role using the endpoint .../admin/role/create  
returns error message of     "message": "policy.error.abilityForbidden",

**Comment by andrechristikan** [comment]
That means your user does not have the ability to create a role.
Check the permissions in the roles entity. Is there a `subject` for the role and `action` for read/create?

More information you can read [casl](https://casl.js.org/v6/en/)

**Comment by solomonmulatu** [comment]
thanks for considering this issue but the user is the default admin user (which is generated by user seed) that has a permission of subject role and action manage so it is possible for Admin to add the new user role, but it is not working.   since manage is the general action that enables any action on the subject

**Comment by andrechristikan** [comment]
Issue approved.
will fix in the next update.
