### ISSUE TITLE
How to create and use API Key?

### ISSUE THREAD

**Issue by sohaib-io** [andrechristikan/ack-nestjs-boilerplate-mongoose#424]
Please help me with How to create and use API Key?

I tried following endpoint:
`/api/v1/admin/api-key/create`

**Comment by andrechristikan** [comment]
In init, you can run migration and seeder.
Then you can use the default api Key.

> Only admins can create new API keys

`2ihKDneb9jQGgidAOqfO` as apiKeyId
`ZLCtDd2rh3TAyVhfAeo3JOPvWfAsTp0Oq6rHl69D` as apiKeySecret.

```
// request headers
{
  'x-api-key': '${apiKeyId}:${apiKeySecret}'
}
```

For creation, you can read in `src/common/api-key/controllers/api-key.admin.controller.ts.`
