### ISSUE TITLE
500 Internal Server for every api endpoint

### ISSUE THREAD

**Issue by blackmouse572** [andrechristikan/ack-nestjs-boilerplate-mongoose#429]
Like the title, i clone the app and start:dev and navigate to /docs. I tried `healthcheck,` `/hello` but all the same

> {
  "statusCode": 500,
  "message": "Internal Server Error",
  "_metadata": {
    "languages": [
      "en"
    ],
    "timestamp": 1685074450439,
    "timezone": "Asia/Saigon",
    "requestId": "adab6ee8-71ba-41d9-8fd5-5e147a06c7fd",
    "path": "/",
    "version": "1",
    "repoVersion": "5.2.3"
  }
}

the console is clean, no error was shown

**Comment by andrechristikan** [comment]
Make sure you have already 
1. run `yarn install` for install dependencies.
2. create `.env` file base on `.env.example`
3. `migration` the data into your database.

If you still getting error
try set the env variable `DEBUGGER_SYSTEM_WRITE_INTO_CONSOLE` and `DEBUGGER_HTTP_WRITE_INTO_CONSOLE` value to `true` for debug with console
