### ISSUE TITLE
E2E And Integration Tests

### ISSUE THREAD

**Issue by solomonmulatu** [andrechristikan/ack-nestjs-boilerplate-mongoose#430]
@andrechristikan What do you think about including integration and E2E tests? Do you have a plan to add it in the most recent versions? I believe that both tests were integrated into the most recent versions.

**Comment by yonashalefom** [comment]
I was thinking about mentioning the same thing for a while. Why are the E2E and Integration Tests are gone?

**Comment by andrechristikan** [comment]
There a lot changes with common modules and it break a lot code in integration test and E2E test.
So i decided to remove them and will refactor it. Maybe will start after i refactor swagger module.
Sorry for that.
