### ISSUE TITLE
How about adding redis store for caching ?

### ISSUE THREAD

**Issue by dcapitator** [andrechristikan/ack-nestjs-boilerplate-mongoose#457]

**Comment by andrechristikan** [comment]
Sure, why not !
I am now on project that used redis for caching, but still in private and not test yet.
After the implementation and tested, i will share it too

**Comment by dcapitator** [comment]
that sounds good , thank you

**Comment by yonashalefom** [comment]
Thank you that is amazing!

**Comment by dcapitator** [comment]
> Sure, why not ! I am now on project that used redis for caching, but still in private and not test yet. After the implementation and tested, i will share it too

r u still working on redis cache?

**Comment by andrechristikan** [comment]
unfortunately, no.
I am running out of time 🥲

**Comment by fedi-dayeg** [comment]
Hello, can you implement Redis cache please ?
