### ISSUE TITLE
Error while running seed if there are other module imported on usermodule

### ISSUE THREAD

**Issue by bipinparajuli** [andrechristikan/ack-nestjs-boilerplate-mongoose#468]

**Comment by andrechristikan** [comment]
All module will start from `AppModule` - `app/app.module.ts`, then `RouterModule`
But for migration will start from `MigrationModule` - `/migartion/migration.module.ts`

So if there module improted in AppModule or RouterModule, you must import too into MigrationModule

Other explaination
main -> app module (common, router, etc)
cli -> migration module (common, seed, etc)
