### ISSUE TITLE
Unable to connect to the database. Retrying (1)...

### ISSUE THREAD

**Issue by kungfu321** [andrechristikan/ack-nestjs-boilerplate-mongoose#503]
Here is my .env file, when run `yarn start:dev` cannot connect to database

![Screenshot 2024-01-02 at 23 34 42](https://github.com/andrechristikan/ack-nestjs-boilerplate/assets/10558363/2da31e69-2154-4bb8-8db4-67a5507adc68)

```
APP_NAME=ACK
APP_ENV=development
APP_LANGUAGE=en
APP_TZ=Asia/Jakarta
APP_MAINTENANCE=false

HTTP_ENABLE=true
HTTP_HOST=localhost
HTTP_PORT= 3000
HTTP_VERSIONING_ENABLE=true
HTTP_VERSION=1

DEBUGGER_WRITE_INTO_FILE=false

JOB_ENABLE=false

DATABASE_HOST=mongodb://localhost:30001,localhost:30002,localhost:30003
DATABASE_NAME=ack
DATABASE_USER=
DATABASE_PASSWORD=
DATABASE_DEBUG=false
DATABASE_OPTIONS=replicaSet=rs0&retryWrites=true&w=majority

AUTH_JWT_SUBJECT=AckDevelopment
AUTH_JWT_ISSUER=ack
AUTH_JWT_AUDIENCE=https://example.com

AUTH_JWT_ACCESS_TOKEN_EXPIRED=1h
AUTH_JWT_ACCESS_TOKEN_SECRET_KEY=123456789012345678901234567890
AUTH_JWT_REFRESH_TOKEN_EXPIRED=182d
AUTH_JWT_REFRESH_TOKEN_SECRET_KEY=098765432112345678901234567890

AUTH_JWT_PAYLOAD_ENCRYPT=false
AUTH_JWT_PAYLOAD_ACCESS_TOKEN_ENCRYPT_KEY=qwerty12345678901234567890
AUTH_JWT_PAYLOAD_ACCESS_TOKEN_ENCRYPT_IV=12345612345678901234567890
AUTH_JWT_PAYLOAD_REFRESH_TOKEN_ENCRYPT_KEY=ytrewq12345678901234567890
AUTH_JWT_PAYLOAD_REFRESH_TOKEN_ENCRYPT_IV=65432112345678901234567890

AWS_S3_CREDENTIAL_KEY=
AWS_S3_CREDENTIAL_SECRET=
AWS_S3_REGION=ap-southeast-3
AWS_S3_BUCKET=
AWS_SES_CREDENTIAL_KEY=
AWS_SES_CREDENTIAL_SECRET=
AWS_SES_REGION=ap-southeast-3

KAFKA_CLIENT_ID=KAFKA_ACK
KAFKA_ADMIN_CLIENT_ID=KAFKA_ADMIN_ACK
KAFKA_BROKERS=localhost:9092
KAFKA_CONSUMER_ENABLE=true
KAFKA_CONSUMER_GROUP=nestjs.ack

SSO_GOOGLE_CLIENT_ID=
SSO_GOOGLE_CLIENT_SECRET=

SENTRY_DSN=
```

**Comment by LuanTruongPTIT** [comment]
Anh vào mongodb của thằng master rồi nhập mongosh tiến hành config nữa ạ

**Comment by LuanTruongPTIT** [comment]
var config = {
    "_id": "dbrs",
    "version": 1,
    "members": [
        {
            "_id": 1,
            "host": "mongo1:27017",
            "priority": 3
        },
        {
            "_id": 2,
            "host": "mongo2:27017",
            "priority": 2
        },
        {
            "_id": 3,
            "host": "mongo3:27017",
            "priority": 1
        }
    ]
};
rs.initiate(config, { force: true });
rs.status();

**Comment by kungfu321** [comment]
> Anh vào mongodb của thằng master rồi nhập mongosh tiến hành config nữa ạ

Thank bạn, mình cũng có thử theo docs làm thế này rồi mà vẫn bị vậy chưa tìm ra nguyên nhân, chắc có lẽ do config gì đó ở máy rồi

**Comment by andrechristikan** [comment]
is this solved?
