### ISSUE TITLE
Issue with 'reflect-metadata' Conflict in NestJS Project and '@nestjs-sentry' Package

### ISSUE THREAD

**Issue by diyorbekrustamjonov** [andrechristikan/ack-nestjs-boilerplate-mongoose#508]
I can't install packages because of reflect-metadata error this package is used in the project new version and in the package '@nestjs-sentry' old version is used there are conflicts.

I have now created an issue in nestjs-sentry to fix this problem. 

![image](https://github.com/andrechristikan/ack-nestjs-boilerplate/assets/74828016/3b8e0c6f-6277-4fe1-9e89-93a97b1b66a7)

**Comment by andrechristikan** [comment]
which version do you have ?
- npm version
- node version
- package.json version

**Comment by diyorbekrustamjonov** [comment]
Node: v20.10.0
NPM: v10.2.3
This package.json: v5.7.0

**Comment by andrechristikan** [comment]
yeah you right.
There is an issue when using `npm`, please use `yarn` instead.

**Comment by andrechristikan** [comment]
for npm use `npm install --legacy-peer-deps` command
then run `npm run start:dev`

Tested on
- npm v10.2.4
- node v20.11.0
