### ISSUE TITLE
Error: ENOENT: no such file or directory, stat 'E:\learning\ack-new\dist\src\languages'

### ISSUE THREAD

**Issue by raju1979** [andrechristikan/ack-nestjs-boilerplate-mongoose#511]
I am getting this error. I have taken fresh pull of this repo. Run `npm install`. run `npm seed`. When I run `npm run start:dev`, I am getting above mentioned error.

**Comment by andrechristikan** [comment]
There is an issue when using `npm`, please use `yarn` instead.

**Comment by andrechristikan** [comment]
#508
