### ISSUE TITLE
Replace Moment.js with Luxon or other better libraries.

### ISSUE THREAD

**Issue by horizon-dev-group** [andrechristikan/ack-nestjs-boilerplate-mongoose#522]
Moment.js is outdated and even the developers of moment.js and moment.js official website states not using moment.js and instead using other libraries. You can check it here https://momentjs.com/docs/#/-project-status/

So if its possible changing moment.js with some other modern and better library would be fantastic.

**Comment by andrechristikan** [comment]
I will consider it, for now lets keep it.
i need time to read the docs and decide it.
