### ISSUE TITLE
Duplicate emails can be registered when registering users

### ISSUE THREAD

**Issue by horizon-dev-group** [andrechristikan/ack-nestjs-boilerplate-mongoose#523]
![image](https://github.com/user-attachments/assets/6a8b3051-6201-4570-a6b9-cad275de6f2a)

As you can see when checking for duplicate emails we gave it an option withDeleted: true, the intention is clear, we don't want duplicate emails even if they're deleted but the thing is the final db query becomes like this:

{"email":{"$regex": /\bexample@mail.com\b/,"$options":"i"},"deleted":true}

there fore the above query will always be false because the emails registerd in our database don't have the property set to true by default. so this will give result of false even if we have an email: example@mail.com

the reason is when we first register with the email: example@mail.com the deleted property is false. but the above query is looking for emails with the deleted property true there for allowing for duplicate emails.

**Comment by horizon-dev-group** [comment]
The solution is to modify the exists code like this or something better:

```
async exists(
        find: Record<string, any>,
        options?: IDatabaseExistOptions
    ): Promise<boolean> {
        if (options?.excludeId) {
            find = {
                ...find,
                _id: {
                    $nin: options?.excludeId ?? [],
                },
            };
        }

        const repository = this._repository.exists(find);

        if (options?.withDeleted) {
            repository.or([
                {
                    deletedAt: { $exists: false },
                },
                {
                    deletedAt: { $exists: true },
                },
            ]);
        } else {
            repository.where('deletedAt').exists(false);
        }

        if (options?.join) {
            repository.populate(
                (typeof options.join === 'boolean' && options.join
                    ? this._join
                    : options.join) as
                    | PopulateOptions
                    | (string | PopulateOptions)[]
            );
        }

        if (options?.session) {
            repository.session(options.session);
        }

        const result = await repository;
        console.log('Result: ' + JSON.stringify(result, null, 2));
        return result ? true : false;
    }
```

**Comment by andrechristikan** [comment]
u rock man
yes, its need some adjustment when check withDeleted in base repository.

i will take a note of it
thanks
