### ISSUE TITLE
Unable to register users when country is provided

### ISSUE THREAD

**Issue by horizon-dev-group** [andrechristikan/ack-nestjs-boilerplate-mongoose#524]
![image](https://github.com/user-attachments/assets/b911e28b-d255-45b2-9fc7-d055b3aaed50)

![image](https://github.com/user-attachments/assets/e5050c9d-7fbc-4bbe-9271-c01e8b53801f)

The code the checks if countries exist or not is the above and it checks if a country is active by checking isActive but there is no property isActive in Country entity making it impossible to register due to the error: "The requested country was not found."

To fix we either have to add isActive or use only findOneById() instead of using findOneActiveById() while registering users.

**Comment by andrechristikan** [comment]
Simply, i remove management country for this project so all country always be active.
