### ISSUE TITLE
API_KEY: xApikey is required.

### ISSUE THREAD

**Issue by ruaruababa** [andrechristikan/ack-nestjs-boilerplate-mongoose#526]
Although, i was add x-api-key to header but result still xApikey is required.
![CleanShot 2024-09-04 at 16 53 31](https://github.com/user-attachments/assets/c057bf21-4bdd-4040-b8aa-60a577f48814)

**Comment by andrechristikan** [comment]
Try use `{key}:{secret}` of the apiKey.
I saw on ur image, u only use the key

Make sure use api key type `public`
