### ISSUE TITLE
NPM Install Throws the bleow Error

### ISSUE THREAD

**Issue by CodyxKarthi** [andrechristikan/ack-nestjs-boilerplate-mongoose#529]
npm install
npm error code ERESOLVE
npm error ERESOLVE unable to resolve dependency tree
npm error
npm error While resolving: ack-nestjs-boilerplate@7.0.0
npm error Found: @sentry/node@8.25.0
npm error node_modules/@sentry/node
npm error   @sentry/node@"^8.25.0" from the root project
npm error
npm error Could not resolve dependency:
npm error peer @sentry/node@"^7.7.0" from @ntegral/nestjs-sentry@4.0.1
npm error node_modules/@ntegral/nestjs-sentry
npm error   @ntegral/nestjs-sentry@"^4.0.1" from the root project
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution.
npm error
npm error
npm error For a full report see:
npm error C:\Users\codyx\AppData\Local\npm-cache\_logs\2024-09-20T16_39_32_548Z-eresolve-report.txt
npm error A complete log of this run can be found in: C:\Users\codyx\AppData\Local\npm-cache\_logs\2024-09-20T16_39_32_548Z-debug-0.log

**Comment by andrechristikan** [comment]
this issue from `ntegral/nestjs-sentry`
on development branch this issue was solved, but not release yet
