### ISSUE TITLE
redis reports error when running on docker

### ISSUE THREAD

**Issue by vfiee** [andrechristikan/ack-nestjs-boilerplate-mongoose#533]
Fllow Installation with Docker
1. cp .env.example .env
2. docker-compose up -d
3. service is error
<img width="1202" alt="image" src="https://github.com/user-attachments/assets/dc7a10c7-1a63-475d-b1be-729428e0f07e">
<img width="1185" alt="image" src="https://github.com/user-attachments/assets/4faa8cb3-c3f8-4a65-a243-757e3639224b">

**Comment by andrechristikan** [comment]
when you're running docker, you need to adjust all `localhost` values with the container name based on the related service.

**Comment by vfiee** [comment]
Thank you for your reply, it's really a really, really great project, thank you for giving! Today I found that the project has been updated to version 7.1. 0, pulled the latest code, started docker under the latest code, copied .env.example to .env and told localhost to modify it to the corresponding container name. Run the yarn install & & yarn start:dev command, commenting bufferLogs: false in main.ts. Got a bug about redis in the console and found [the related problem](https://github.com/redis/node-redis/issues/2624) in node-redis, but it doesn't have the correct solution. Looking forward to hearing from you and getting it resolved correctly.

```log
[Nest] 20295  - 2024/11/06 14:09:59     LOG [InstanceLoader] AppMiddlewareModule dependencies initialized +1ms
node:events:497
      throw er; // Unhandled 'error' event
      ^

SocketClosedUnexpectedlyError: Socket closed unexpectedly
    at Socket.<anonymous> (/Users/vyron/Study/ack-nestjs-boilerplate/node_modules/@redis/client/dist/lib/client/socket.js:194:118)
    at Object.onceWrapper (node:events:634:26)
    at Socket.emit (node:events:519:28)
    at TCP.<anonymous> (node:net:339:12)
Emitted 'error' event on Commander instance at:
    at RedisSocket.<anonymous> (/Users/vyron/Study/ack-nestjs-boilerplate/node_modules/@redis/client/dist/lib/client/index.js:422:14)
    at RedisSocket.emit (node:events:519:28)
    at RedisSocket._RedisSocket_onSocketError (/Users/vyron/Study/ack-nestjs-boilerplate/node_modules/@redis/client/dist/lib/client/socket.js:218:10)
    at Socket.<anonymous> (/Users/vyron/Study/ack-nestjs-boilerplate/node_modules/@redis/client/dist/lib/client/socket.js:194:107)
    at Object.onceWrapper (node:events:634:26)
    at Socket.emit (node:events:519:28)
    at TCP.<anonymous> (node:net:339:12)

Node.js v20.17.0

```

**Comment by andrechristikan** [comment]
there was a problem running this project with docker,.
so i updated the readme.

now i use docker to run dependencies, only mongodb and redis.

please read and follow the new instructions, then everything will be fine.

thanks

**Comment by vfiee** [comment]
Finally, it ran successfully! It's really a great project. Thank you for your efforts!
The following are the modification steps for normal service access.
1. pull latest code
2. rm .env dir
3. copy .env.example to .env
4. modify 3 env (DATABASE_URL=mongodb://host.docker.internal:27017,host.docker.internal:27018,host.docker.internal:27019/ack?retryWrites=true&w=majority&replicaSet=rs0,REDIS_HOST=redis,HTTP_HOST=0.0.0.0)
5. run docker compose up -d
6. Http Server will running on http://127.0.0.1:3000

**Comment by andrechristikan** [comment]
Thats cool!
anw thanks
